experiment:
  runs: 200
  horizon: 200
  seed: 42
  output_dir: results/multi/mirzae_2026E/figure3
  add_opt: false
  order: [OUCB, SBLFE, TS, UCB, non_learner]

environment:
  n_arms: 10
  delta: 0.2
  best_mean: 0.9
  probs: [ 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9 ]

agents:
  - name: OUCB
    class: OUCB
    observes: [non_learner]
    params:
      nbr_neighbours: 1
      c: 2.0
      gamma: 0.5

  - name: SBLFE
    class: SBLFE
    observes: [non_learner]
    params:
      beta: 1.0
      lambda_param: 0.5
      epsilon: 0.1

  - name: tucb
    class: TUCB
    observes: [non_learner]
    params:
      nbr_neighbours: 1

  - name: TS
    class: TS

  - name: UCB
    class: UCB1

  - name: non_learner
    class: alphaOptimal
    params:
      alpha: 1
