experiment:
  seed: 40
  n_jobs: 4
  output_dir: results/multi/current/mistral
  horizon: 500
  runs: 20
  order: [ucb, Greedy, ts ,Mistral]
  track_other_actions_for: ["ucb", "Greedy", "ts"]
  add_opt: False

environment:
  n_arms: 5
  delta: 0.2
  best_mean: 0.6
  probs: [0.4, 0.4, 0.6, 0.4, 0.4]

agents:
  - name: ucb
    class: UCB
  - name: ts
    class: TS
  - name: Greedy
    class: Greedy
  - name: Mistral
    class: LLM
    prompt: default
    params:
      model: mistralai/Mistral-7B-Instruct-v0.2