experiment:
  seed: 40
  n_jobs: 4
  output_dir: results/multi/figure1_llm
  horizon: 500
  runs: 20
  interaction: sequential
  order: [ucb1,Greedy, ts ,llm_history]
  output_dir: results/multi/llm_ucb_history
  track_other_actions_for: [ucb, Greedy, ts]

environment:
  n_arms: 5
  delta: 0.2
  best_mean: 0.6
  probs: [0.6, 0.4, 0.4, 0.4, 0.4]

agents:
  - name: ucb1
    class: UCB1
  - name: ts
    class: TS
  - name: Greedy
    class: Greedy
  - name: llm_history
    class: LLM
    prompt: history
    params:
      model: Qwen/Qwen2.5-7B-Instruct